<a href="https://colab.research.google.com/github/aadarshraghunathan/Neural-decision-making/blob/main/icnm_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pylab inline 
import random 

Populating the interactive namespace from numpy and matplotlib


Part 1: Setting up the neuron network 

In [ ]:
class MP_Neuron:
  def __init__(self,state,id):
    self.state = state
    self.id = id 

def update(neuron_id,theta): ### update for the ith neuron , theta is the global inhibition factor 
  global neuron_list,adj_mat,N
  update_val = 0
  weight_sum = 0 
  state_sum = 0 
  for j in range(N):
    update_val += (neuron_list[j].state)*adj_mat[neuron_id][j] 
    weight_sum += adj_mat[neuron_id][j]
    state_sum += neuron_list[j].state

  update_factor = update_val/weight_sum
  inhibit_factor = (state_sum/N)**2
  # print(inhibit_factor)
  inhibit_factor /= theta
  print(update_factor)
  print(inhibit_factor)
  if update_factor > inhibit_factor:
    neuron_list[neuron_id].state = 1
  else:
    neuron_list[neuron_id].state = 0 
  if(neuron_list_copy[neuron_id].state != neuron_list[neuron_id].state):
    print("Change")

    



In [ ]:
### creating all the neurons 
neuron_list = []
neuron_list_copy = []
N = 1000 ### number of neurons in the network
for i in range(N):
  ### randomise inital state, with 0.13(theta) probability of firing  
  rand_state =  random.uniform(0,1)
  if rand_state < 0.13 :
    state = 1 
  else :
    state = 0
  neuron = MP_Neuron(state,i)
  neuron_list.append(neuron)
  neuron_list_copy.append(neuron)
  


In [ ]:
### creating the graph between the neurons by making an adjacency matrix 
adj_mat = np.zeros((N,N), dtype = int )

### setting the connections with probability 0.36 (so far not considering attractor networks)
for i in range(N):
  for j in range(N):
    rand_connection = random.uniform(0,1)
    if rand_connection < 0.36:
      adj_mat[i][j] = 1 
    else :
      adj_mat[i][j] = 0 

print(adj_mat)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]]


In [ ]:
### initialising the random time delays for updates 
### if neuron is active , use l1 = 0.07 
### if neuron is not active  , use l2 = 0.005

l1 = 0.07 
l2 = 0.005 

time_update = np.zeros((N))
for i in range(N):
  if(neuron_list[i].state == 1 ):
    t = np.random.exponential(scale = 1/l1)
    time_update[i]= int(t)
  else:
    t = np.random.exponential(scale = 1/l2)
    time_update[i] = int(t)
print(time_update)


[1.190e+02 1.580e+02 1.390e+02 2.180e+02 2.500e+01 4.200e+01 4.560e+02
 8.700e+01 1.800e+01 1.190e+02 2.770e+02 2.910e+02 2.780e+02 2.600e+01
 1.030e+03 1.110e+02 3.100e+01 1.790e+02 1.050e+02 1.020e+02 3.900e+01
 1.560e+02 2.100e+01 6.000e+00 1.400e+01 1.230e+02 2.920e+02 8.620e+02
 1.720e+02 1.830e+02 4.500e+01 3.420e+02 6.200e+01 2.880e+02 1.260e+02
 8.900e+01 7.700e+01 2.250e+02 1.290e+02 3.100e+01 3.400e+01 6.840e+02
 5.000e+00 3.000e+00 7.000e+00 2.250e+02 2.110e+02 7.000e+00 2.180e+02
 1.140e+02 2.050e+02 2.700e+01 3.440e+02 2.700e+02 3.100e+01 1.110e+02
 2.430e+02 2.000e+01 3.720e+02 1.400e+01 1.600e+01 5.900e+01 4.330e+02
 1.350e+02 1.360e+03 8.100e+01 2.730e+02 2.960e+02 6.300e+01 2.180e+02
 5.200e+02 3.700e+01 5.000e+00 1.630e+02 1.000e+01 1.890e+02 8.300e+01
 1.000e+00 0.000e+00 7.250e+02 8.500e+01 1.450e+02 2.600e+01 2.030e+02
 3.260e+02 1.400e+01 5.000e+00 2.350e+02 0.000e+00 1.360e+02 3.250e+02
 5.900e+01 1.150e+02 1.340e+02 1.300e+01 7.500e+01 8.800e+01 2.580e+02
 1.000

In [ ]:
### updating all the neurons 
### after updating the value , update the values in the time_update array 
check_update = np.zeros(1000)
for t in range(100000):
  print(t)
  for i in range(N):
    if(time_update[i] == t):
      # print("yeet")
      update(i,1.3)
      check_update[i] += 1
      if(neuron_list[i].state == 1 ):
       x = np.random.exponential(scale = 1/l1)
       time_update[i] += int(x)
      else:
       x = np.random.exponential(scale = 1/l2)
       time_update[i] += int(x)


0
1.0
0.7692307692307692
1
1.0
0.7692307692307692
2
1.0
0.7692307692307692
3
1.0
0.7692307692307692
1.0
0.7692307692307692
4
1.0
0.7692307692307692
5
1.0
0.7692307692307692
6
1.0
0.7692307692307692
7
1.0
0.7692307692307692
8
1.0
0.7692307692307692
1.0
0.7692307692307692
9
1.0
0.7692307692307692
10
11
1.0
0.7692307692307692
12
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
13
1.0
0.7692307692307692
1.0
0.7692307692307692
14
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
15
1.0
0.7692307692307692
1.0
0.7692307692307692
16
1.0
0.7692307692307692
17
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
18
1.0
0.7692307692307692
1.0
0.7692307692307692
19
1.0
0.7692307692307692
1.0
0.7692307692307692
20
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
21
1.0
0.7692307692307692
22
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
1.0
0.7692307692307692
23
1.0
0.769230769230

KeyboardInterrupt: ignored

In [ ]:
print(check_update)

[ 12. 474.  63.  30. 216. 124.  12.   1. 400. 105. 382.  95. 192. 183.
  12.  32. 266. 146. 323.  85.  33. 544. 343. 227. 479.  80.  49.  16.
   2. 224. 245. 139. 532.  77. 147.  67. 330. 219. 477.   3. 312.   6.
  27. 312.   3.  16. 502.  41. 196. 158.   4.  88.  13.  75.  69.  10.
  13. 438. 243.  24.  47. 179.   1.  86. 244.  12.  14. 439. 232.  39.
 505.  18.  12.   2. 125. 128. 308.  50.   1. 148.   8.  44. 227.  40.
  17. 239.  58.  55.  11. 278. 144. 502. 251. 221. 171.   4. 372.   1.
 167.  10.  76. 196.  91.  73.  54. 231.  68.  54. 457. 126. 151. 128.
  35. 121.  82.  51. 111. 447.  68. 210.   3. 531.   6. 154. 235.   4.
  99.   4.  54. 488. 494. 339. 289. 307.  18.  38. 430.   5. 146. 102.
 449.  35. 343. 135. 143. 302.   8.  30. 422. 232. 158.   3.  35. 521.
 208.  14. 275. 209.  18.   1. 338.   2.  20. 146. 127.  98.  37. 303.
   3. 210. 109. 239.  28. 130. 476. 198. 471. 297.  61. 244.  68.  93.
   6.  57.   3. 400. 157.  54.  61. 287. 282. 187. 384. 176.  16.  92.
  14. 

In [ ]:
for i in neuron_list:
  print(i.state, end= " ")
print("")
for j in neuron_list_copy:
  print(j.state, end = " ")

1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 

Part 2: Simulating the decision making process

In [ ]:
### functions to create the two attractor regions , and also update the graph weights when the attractor sets are created 
def create_attractor_sets():
  choice = [i for i in range(1000)]
  A = []
  B = []
  for i in range(100):
    picked = np.random.choice(choice) 
    A.append(picked)
    choice.remove(picked)

  for i in range(100):
    picked = np.random.choice(choice)
    B.append(picked)
    choice.remove(picked)
  
  return A,B

def update_weights(A,B):
  global adj_mat
  for i in range(100):
    for j in range(100):
      rand_connection = random.uniform(0,1)
      if rand_connection < 0.55:
        adj_mat[A[i]][A[j]] = 1 
        adj_mat[B[i]][B[j]] = 1 
      else :
        adj_mat[A[i]][A[j]] = 0 
        adj_mat[B[i]][B[j]] = 0 





In [ ]:
### create the attractor sets 
A,B = create_attractor_sets()
### update the graph weights 
update_weights(A,B)



In [ ]:
### function to create the two stimulus sets Sa and Sb 
### these sets are of random size in the range 1-100
### also function to update connections between the stimulus and the attractor sets 

def create_stimulus(A,B):
    choice = [i for i in range(1000)]
    for i in A:
      choice.remove(i)
    for j in B:
      choice.remove(j)
    size_SA = np.random.binomial(20,0.5)
    size_SB = np.random.binomial(20,0.5)
    SA = []
    SB = [] 
    for i in range(size_SA):
      picked = np.random.choice(choice)
      SA.append(picked)
      neuron_list[picked].state =1 
      choice.remove(picked)
    for i in range(size_SB):
      picked = np.random.choice(choice)
      SB.append(picked) 
      neuron_list[picked].state = 1 
      choice.remove(picked)

    return SA,SB

def update_weights_stimulus(A,B,SA,SB):
    global adj_mat
    for i in SA:
      for j in A:
        rand_connection = random.uniform(0,1)
        if rand_connection < 0.55:
          adj_mat[i][j] = 1 
        else :
          adj_mat[i][j] = 0 

    for i in SB:
      for j in B:
        rand_connection = random.uniform(0,1)
        if rand_connection < 0.55:
          adj_mat[i][j] = 1 
        else :
          adj_mat[i][j] = 0 



      


    

In [ ]:
### create the stimulus for the simulation 
SA,SB = create_stimulus(A,B)
### update all the connections between the stimulus set and the attractor set
update_weights_stimulus(A,B,SA,SB)
print(SA)
print(SB)

[412, 129, 438, 969, 744, 923, 251, 754, 231, 863, 307, 125]
[921, 954, 748, 555, 779, 689, 685, 423, 224, 53, 966]


Now, we need to decide the winner. To do this , run 100000 updates and if one set A or B dominates the other for 500 consecutive steps, they are declared the winner .

In [ ]:
time_update = np.zeros((N))
for i in range(N):
  if(neuron_list[i].state == 1 ):
    t = np.random.exponential(scale = 1/l1)
    time_update[i]= int(t)
  else:
    t = np.random.exponential(scale = 1/l2)
    time_update[i] = int(t)

In [ ]:
### function to check which decision is winning 
### return 1 for A winning , 0 for no decision , -1 for B winning
def check_winner(A,B):
  sum_A = 0 
  sum_B = 0
  for i in A:
    sum_A += neuron_list[i].state
  for j in B:
    sum_B += neuron_list[j].state

  sum_A /= 100
  sum_B /= 100 
  print(sum_A)
  print(sum_B)
  if(sum_A - sum_B >= 0.75):
    return 1 
  elif(sum_B - sum_A >= 0.75):
    return -1
  else:
    return 0 



In [ ]:
### updating all the neurons 
### after updating the value , update the values in the time_update array

for t in range(100000):
  for i in range(N):
    if(time_update[i] == t):
      if(i in SA or i in SB):
        continue
      update(i,1)
      if(neuron_list[i].state == 1 ):
       t = np.random.exponential(scale = 1/l1)
       time_update[i] += int(t)
      else:
       t = np.random.exponential(scale = 1/l2)
       time_update[i] += int(t)
      
  if(check_winner(A,B) != 0 ):
    print("YAY")
  for i in A:
    print(neuron_list[i].state, end=" ")

Streaming output truncated to the last 5000 lines.
1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0.68
0.66
1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0.68
0.66
1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0.68
0.66
1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0.68
0.66
1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0

KeyboardInterrupt: ignored